name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Checkout source code
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright tests with HTML report
      - name: Run Playwright tests
        run: CI=true xvfb-run npx playwright test --reporter=html
        continue-on-error: true  # still deploy even if tests fail

      # Upload report artifact for debugging
      - name: Upload Playwright report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report

      # Deploy to GitHub Pages (gh-pages branch)
      - name: Deploy Playwright report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
